enable: true
overwrite-commands:
  kick: true
  list: true
  transferserver: true
  msg: true
  ping: true
  # This command is currently in Beta and should not be enabled!
  connect: false
command-config:
  kick:
    permission: bungeetools.kick
    noperm-message: "§cYou are not allowed to use this command!"
    success-message: "§cSuccessfully kicked {player} for {reason}"
    usage: "§cUse /kick <Player> <Reason>"
    description: "kick a player from the network"
  connect:
    permission: bungeetools.connect
    noperm-message: "§cYou are not allowed to use this command!"
    usage: "§cUse /connect <Server>"
    description: "Switch to another server"
  ping:
    permission: bungeetools.ping
    noperm-message: "§cYou are not allowed to use this command!"
    usage: ""
    description: "Get your latency to the network!"
  list:
    permission: bungeetools.list
    noperm-message: "§cYou are not allowed to use this command!"
    usage: "§cUse /list <Server>"
    description: "Get Server / Networks Players"
  msg:
    permission: bungeetools.msg
    noperm-message: "§cYou are not allowed to use this command!"
    usage: "§cUse /msg <Player> <Message>"